# Configuration Auth-Server
server.port=8090

# Configuration Base de données (Propagées à DatabaseManager via variables d'env ou utilisées si Spring Data était utilisé)
# Note: DatabaseManager dans DB-Core utilise ses propres fallbacks, mais on peut les configurer ici si on veut.
db.url=jdbc:mysql://localhost:3306/messagerie?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=mailuser
db.pass=mailpass

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.example=DEBUG
